### ISSUE TITLE
ISR: Prerendering + FileSystemCacheHandler error

### ISSUE THREAD

**Issue by Ruchha** [rx-angular/rx-angular#1815]
# Description
Getting error on server start

# Steps to Reproduce the Issue
Im trying to reproduce code from documentation
```ts
const fsCacheHandler = new FileSystemCacheHandler({
  cacheFolderPath: join(browserDistFolder, '/cache'),
  prerenderedPagesPath: browserDistFolder,
  addPrerenderedPagesToCache: true,
});
```
```ts
const isr = new ISRHandler({
    indexHtml,
    invalidateSecretToken: 'MY_TOKEN',
    enableLogging: true,
    serverDistFolder,
    browserDistFolder,
    bootstrap,
    commonEngine,
    cache: fsCacheHandler
  });
  ```
  Then im adding prerender configuration
  ```
 "prerender": {
    "routesFile": "routes.txt",
    "discoverRoutes": false
},
```
routes.txt file:
```
/news
```
```ng build``` then run ```node server.mjs```
```
Cache folder does not exist. Creating...
Adding prerendered pages to cache...
node:fs:2982
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, copyfile 'C:\Users\user\isr-example\dist\isr-example\browser\news\index.html' -> 'C:\Users\user\isr-example\dist\isr-example\browser\cache\news\index.html.html'
    at Module.copyFileSync (node:fs:2982:3)
    at Ce.transferPrerenderedPagesToCacheFolder (file:///C:/Users/user/isr-example/dist/isr-example/server/chunk-J5AJIJJH.mjs:3:3411)
    at Ce.addPrerenderedPagesToCache (file:///C:/Users/user/isr-example/dist/isr-example/server/chunk-J5AJIJJH.mjs:3:2483)
    at Ce.populateCacheFromFilesystem (file:///C:/Users/user/isr-example/dist/isr-example/server/chunk-J5AJIJJH.mjs:3:2242)
    at new Ce (file:///C:/Users/user/isr-example/dist/isr-example/server/chunk-J5AJIJJH.mjs:3:942)
    at U_ (file:///C:/Users/user/isr-example/dist/isr-example/server/server.mjs:108:5202)
    at file:///C:/Users/user/isr-example/dist/isr-example/server/server.mjs:108:5834
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7) {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'C:\\Users\\user\\isr-example\\dist\\isr-example\\browser\\news\\index.html',
  dest: 'C:\\Users\\user\\isr-example\\dist\\isr-example\\browser\\cache\\news\\index.html.html'
}
```

# Environment
Angular 18.2.12
@rx-angular/isr 18.1.0
node 18.20.3

**Comment by prophet-99** [comment]
I have the same problem, any update?:

```
$ node dist/angular-isr/server/server.mjs
Cache folder does not exist. Creating...
Adding prerendered pages to cache...
node:fs:3029
  binding.copyFile(
          ^

Error: ENOENT: no such file or directory, copyfile 'C:\Users\ACER\Desktop\angular-isr\dist\angular-isr\browser\prerrender\index.html' -> 'C:\Users\ACER\Desktop\angular-isr\dist\angular-isr\server\custom-cache\prerrender\index.html.html'
```
