### ISSUE TITLE
RxJS 7 Support

### ISSUE THREAD

**Issue by Quraian** [rx-angular/rx-angular#470]
Right now when I try to upgrade RxJS in my Angular 11.1 application it fails on:

```
An error occurred during the build:
Error: The target entry-point "@rx-angular/template" has missing dependencies:
 - rxjs/internal/types

    at TargetedEntryPointFinder.findEntryPoints (C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:28:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\Code\TEST\src\Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\Code\TEST\src\Web\ClientApp\node_modules\@ngtools\webpack\src\ngcc_processor.js:163:16)
    at C:\Code\TEST\src\Web\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:55:18
    at C:\Code\TEST\src\Web\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:47:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\Code\TEST\src\Web\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:45:32)
    at C:\Code\TEST\src\Web\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:38:55
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\Code\TEST\src\Web\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:37:32)
An unhandled exception occurred: The target entry-point "@rx-angular/template" has missing dependencies:
 - rxjs/internal/types
```

**Comment by BioPhoton** [comment]
It should be fixed now. can u confirm?

**Comment by Quraian** [comment]
It seems to work fine now.
Thanks Michael!

**Comment by intellix** [comment]
Are you sure this library supports RxJS 7? I'm seeing that @rx-angular/cdk@1.0.0-alpha.11 depends on RxJS 6.6.7 and I'm getting errors about observables/operators used within that library aren't Observables (multiple versions where Observable !== Observable checks)
