### ISSUE TITLE
rxLet `ComponentFixture` error: "Cannot read property 'nativeElement' of null"

### ISSUE THREAD

**Issue by edbzn** [rx-angular/rx-angular#714]
# Description

Hi there, 

I have trouble with the `LetDirective` in a testing environment, when I try to query the native element to test the DOM I face the following error (using Karma/Jasime): 

```
TypeError: Cannot read property 'nativeElement' of null
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:21:48)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
            at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:123:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:545:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:560:1)
```

Using Jest I get another output, maybe more verbose: 

```
 TypeError: Cannot read property 'nativeElement' of null

      19 |     fixture.detectChanges();
      20 |     expect(
    > 21 |       fixture.debugElement.query(By.css('div')).nativeElement.innerHTML
         |                                                ^
      22 |     ).toContain('hello');
      23 |   });
      24 | });

      at src/app/app.component.spec.ts:21:48
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:143:47)

```

Here is the test: 

```ts
describe('AppComponent', () => {
  let fixture: ComponentFixture<AppComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [LetModule, PushModule],
      declarations: [AppComponent],
    }).compileComponents();
  });

  it('render "hello" text', () => {
    fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    expect(
      fixture.debugElement.query(By.css('div')).nativeElement.innerHTML
    ).toContain('hello');
  });
});
```

The template : 

```html
<div *rxLet="state$ as state">
  {{ state }}
</div>

<!-- ❌ This is also failing: 
<div *rxLet="state$ as state">
  {{ state }}
</div>
--> 

<!-- ✅ Btw this is working:
  <div *ngIf="state$ | async as state">
  {{ state }}
</div>
-->

<!-- ✅ This is also working:
<div *ngIf="state$ | push as state">
  {{ state }}
</div>
-->
```

And the component:

```ts
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  state$ = of('hello');
}
```

Using the `PushPipe` or `AsyncPipe` resolves the issue and the test is passing.

# Steps to Reproduce the Issue

Here is [the full repro](https://github.com/edbzn/rxlet-test-failure-repro), there's a branch named **jest** to show the different outputs.

# Related to Other Issues

N/A

# Tasks to Resolve This

That's the question, let me know if you have any clue.

# Notes

N/A

**Comment by hoebbelsB** [comment]
@edbzn thx for the finding! What strategy is active during tests? Is it normal? Then the problem lies in the fact, that rxLet will create its template not sync, but scheduled. 
There are two options now:
* use the renderCallback and check the div afterwards
* use a strategy which emits instant (e.g. native)

**Comment by edbzn** [comment]
> What strategy is active during tests? Is it normal? 

The default strategy "local", I didn't set one on my own.

> Then the problem lies in the fact, that rxLet will create its template not sync, but scheduled.

I thought about it, so trivially I tried to defer the test like this : 

```ts
  it('render "hello" text', (done) => {
    fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    setTimeout(() => {
      expect(
        fixture.debugElement.query(By.css('div')).nativeElement.innerHTML
      ).toContain('hello');
      done();
    }, 1000)
  });
```

But I still get the error. 

> use the renderCallback and check the div afterwards

What would be the solution using the renderCallback, can you share a small code snippet?

> use a strategy which emits instant (e.g. native)

Yes! it works using the "native" strategy, but that's a solution I want to avoid since I loose the performance boost.

**Comment by hoebbelsB** [comment]
The renderCallback is a property on the `rxLet` directive which informs you about when the directive finished rendering.

Use it like this:
```html
<div *rxLet="data$; let data; renderCallback: rb">

</div>

```

```ts
@Component({})
export class Component {

  readonly rb = new Subject();

  constructor() {
   this.rb.subscribe(() => {
    // check for div, since it got rendered.
    // be aware, updates will trigger this as well. If you need only the first, use take(1) :)
   });
  }

}
```

Usage in the test would be the same:

```ts

it('render "hello" text', (done) => {
    fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    fixture.rb.subscribe(() => {

    // check div
    done();
    });
  });
```
But please be aware that there are issues with some of the strategies running in test-environments... we need to document more on that! The local one has its own issues, the concurrent strategies rely on the `MessageChannel` to get polyfilled.

I would recommend using the native strategy for tests for now and `normal` otherwise if you really want to have the performance benefits :)

**Comment by edbzn** [comment]
Thanks for the examples, I will try it soon to see if it fixes the issue. 

Regarding the solution using the `renderCallback`, it forces to change the actual component implementation to make the test working, it's weird to add code just for testing purposes. There's no other solution that only relies on test implementation?

For example, I think about providing a `TestingStrategyProvider` that automatically setup the render strategy to "native": 

```ts
await TestBed.configureTestingModule({
   providers: [{ provide: StrategyProvider, useClass: TestingStrategyProvider  }]
}).compileComponents();
```

Then I don't need to touch the component to test it, could it be possible?

**Comment by edbzn** [comment]
I tested, it works like a charm : 

```typescript
@Injectable()
class TestingStrategyProvider extends RxStrategyProvider {
    constructor() {
        super({ primaryStrategy: 'native' });
    }
}
```

```typescript
await TestBed.configureTestingModule({
   ...
   providers: [{ provide: StrategyProvider, useClass: TestingStrategyProvider  }]
}).compileComponents();
```

This way I can leave the component implementation as it and the app environment still use the "local" strategy.

**Comment by bryanforbes** [comment]
I'm having a similar problem. I set up my component with the `renderCallback` and focus the input once that happens and it works pretty well (I have other uses, but focus is easily evident):

https://stackblitz.com/edit/angular-ivy-iq2nef

However there are problems in testing:

https://stackblitz.com/edit/angular-ivy-uflees

As you can see, with the default strategy, rendering is delayed and I have to wait for the `renderCallback` observable to emit. It's less than ideal, so I tried the `native` strategy, but none of the ideas I've tried works. The only way I can get the `native` strategy to work is to insert a `setTimeout()` before testing if the element is focused. This seems wrong. I was under the impression that the `native` strategy was synchronous. Could I be doing something differently in my test?

**Comment by edbzn** [comment]
Related to #1314 and #726
